name: Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python
      run: uv python install 3.12
    - name: Install dependencies
      run: uv sync --all-extras
    - name: Build documentation
      run: uv run properdocs build -f properdocs.yml
