name: Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install uv
      uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python
      run: uv python install 3.12
    - name: Install dependencies
      run: uv sync --extra docs --locked --python 3.12
    - name: Build documentation
      run: uv run --python 3.12 properdocs build -f properdocs.yml
